config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    # Protect against timing attacks:
    # - See https://codahale.com/a-lesson-in-timing-attacks/
    # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
    # - Use & (do not use &&) so that it doesn't short circuit.
    # - Use digests to stop length information leaking (see also ActiveSupport::SecurityUtils.variable_size_secure_compare)
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
  end
  mount Sidekiq::Web, at: '/sidekiq'

  # Return 404 at root path
  get '/', to: proc { [404, {}, ['']] }

  # Auth0
  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure'        => 'auth0#failure'

  # webhooks
  match '/webhooks/:id', to: 'webhook#process_webhook', via: :post, as: 'webhook'

  # payments
  match '/payments/:id/pay', to: 'payments#pay', via: %i[get post], as: 'pay'
  match '/processors/:id/example', to: 'processor#example', via: :get, as: 'example'

  # admin
  ActiveAdmin.routes(self)
  match '/admin/login', to: 'auth0#login', via: :get
  match '/admin/logout', to: 'auth0#logout', via: :get
end

app/views/stripe/example.html.erb

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Donate to us | The People's Org</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <style>
      body .content .container,
      body .content #disclaimer {
        margin-top: 50px;
      }
      .fat-text {
        font-weight: 700;
      }
      .large-text {
        font-size: 1.4em;
      }
      .dark {
        background: rgb(52, 58, 64);
        color: rgb(255, 255, 255);
      }
      p.donation-amount {
        cursor: pointer;
      }
      button {
        cursor: pointer;
      }
      p.input-label {
        font-weight: 600;
      }
      #footer {
        height: 150px;
      }
    </style>
  </head>
  <body>
    <!-- NAVBAR -->
    <nav class="navbar navbar-expand-md navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">The People's Org</a>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Campaigns</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">News</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="#">Donate</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About Us</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="content">
      <div class="container">
        <!-- Donate boxes -->
        <div class="row">
          <div class="col help-text">
            <h2 class="fat-text">Can you chip in?</h2>
            <p class="large-text text-justify">Thousands of us from across the world have already chipped in to help fund the staff, the tech and website. Will you chip in to make sure we can move fast to win the campaigns that matter to all of us? You can make a secure donation here!</p>
            <img src="image.png" class="img-fluid">
          </div>
          <div class="col">
            <div class="donate-box border border-dark rounded">
              <div class="donation-amount-form">
                <h2 class="fat-text dark text-center p-3" id="donation-header">I'm donating $<span id="donation-amount">0</span></h2>
                <div class="donation-amounts">
                  <p class="fat-text large-text pl-3">Choose your donation amount</p>
                  <div class="row ml-1 mr-1">
                    <div class="col">
                      <p class="p-2 rounded dark text-center donation-amount" data-donation-amount="5">$5</p>
                    </div>
                    <div class="col">
                      <p class="p-2 rounded dark text-center donation-amount" data-donation-amount="10">$10</p>
                    </div>
                    <div class="col">
                      <p class="p-2 rounded dark text-center donation-amount" data-donation-amount="15">$15</p>
                    </div>
                  </div>
                  <div class="row ml-1 mr-1">
                    <div class="col">
                      <p class="p-2 rounded dark text-center donation-amount" data-donation-amount="20">$20</p>
                    </div>
                    <div class="col">
                      <p class="p-2 rounded dark text-center donation-amount" data-donation-amount="50">$50</p>
                    </div>
                    <div class="col">
                      <p class="p-2 rounded dark text-center donation-amount" data-donation-amount="100">$100</p>
                    </div>
                  </div>
                  <div class="row ml-1 mr-1 pl-3">
                    <label class="form-check-label">
                      <input type="checkbox" class="form-check-input" id="recurring">
                      Make it monthly?
                    </label>
                  </div>
                  <div class="pay-button text-center mb-3">
                    <button type="button" id="pay-with-card-button" class="btn btn-dark m-auto pl-4 pr-4 pt-2 pb-2">Pay With Card</button>
                  </div>
                </div>

                <div class="card-details ml-3">
                  <p class="fat-text large-text">Thanks, we just need a few more details</p>
                  <div class="row">
                    <div class="col">
                      <p class="input-label">Credit Card Details</p>
                    </div>
                    <iframe src="/payments/<%= @processor.id %>/pay?key=<%= @api_key %>" class="col-8 credit-card" frameBorder="0" scrolling="no" height="200">
                    </iframe>
                  </div>
                  <input type="hidden" id="source_system" value="dopaisa_hosted">
                  <input type="hidden" id="source_external_id" value="123">
                  <div class="pay-button text-center mb-3">
                    <button type="button" id="pay-button" class="btn btn-dark m-auto pl-5 pr-5 pt-2 pb-2" data-loading-text="Processing...">Pay</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div id="disclaimer">
            <p>We want to be transparent and accountable about how we spend your donations - for more information please see our Donation Policy.</p>
            <p>Your personal information will be kept private and held securely. By submitting information you are agreeing to The People's Org keeping you informed about campaigns and agree to the use of cookies in accordance with our privacy policy. </p>
          </div>
        </div>
      </div>


      <footer id="footer" class="dark">
        <div class="container">
        </div>
      </footer>

      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

      <script>
        $(function() {
          $(".card-details").hide();

          $("#pay-with-card-button").click(function() {
            $(".card-details").show();
            $(".donation-amounts").hide();
          });

          $("p.donation-amount").click(function() {
            var donationAmountText = $(this).data("donation-amount");
            window.donationAmount = donationAmountText * 100;
            $("span#donation-amount").text(donationAmountText);
          });

          $("#pay-button").click(function() {
            var iframeWindow = $("iframe.credit-card")[0].contentWindow;
            var metadata = {
              name: $("input#name").val(),
              email: $("input#email").val()
            };
            var source = {
              system: $("input#source_system").val(),
              external_id: $("input#source_system").val()
            };
            var data = {
              action: "submit",
              donationAmount: window.donationAmount,
              metadata: metadata,
              source: source,
              recurring: $("#recurring").is(":checked")
            };

            console.log("Submitting from parent window")
            iframeWindow.postMessage(data, "*");
          });

          window.addEventListener("message", function(event) {
            var data = event.data;
            if (data.action === "donationProcessed") {
              var response = JSON.parse(data.response);
              console.log(response);
              alert("Thank you for your donation, your transaction id is: " + response.transaction_id);
            }
          }, false);
        });
      </script>
  </body>
</html>

app/views/stripe/pay.html.erb
<html>
  <head>
    <script src="https://js.stripe.com/v3/"></script>
    <script
      src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous"></script>
    <script 
      src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.bundle.min.js"
      integrity="sha256-uz0BcnPtSHZ02XZthAHPRYIoWWrcwMOmAk9ErnFQkNs="
      crossorigin="anonymous"></script>
    <link 
      rel="stylesheet" 
      href="https://use.fontawesome.com/releases/v5.0.9/css/all.css" 
      integrity="sha384-5SOiIsAziJl6AWe0HWRKTXlfcSHKmYV4RBF18PPJ173Kzn7jzMyFuTtk8JA7QQG1" 
      crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <style>
      body {
        margin: 0;
      }      
      .row {
        display: -ms-flexbox;
        display: flex;
        margin: 0 5px 10px;
      }
      .field {
        position: relative;
        width: 100%;
        height: 2.5rem;
        margin: 0 10px;
        background: #fff;
        border-radius: 4px;
      }
      .field.half-width {
        width: 50%;
      }

      .baseline {
        position: absolute;
        width: 100%;
        height: 1px;
        left: 0;
        bottom: 0;
        background-color: transparent;
        transition: background-color 0.3s cubic-bezier(0.165, 0.84, 0.44, 1);
        border-bottom-left-radius: 4px;
        border-bottom-right-radius: 4px;
      }

      label {
        position: absolute;
        width: 100%;
        left: 7px;
        bottom: 8px;
        color: #555;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
        transform-origin: 0 50%;
        cursor: text;
        transition-property: color, transform;
        transition-duration: 0.3s;
        transition-timing-function: cubic-bezier(0.165, 0.84, 0.44, 1);
        font-family: Montserrat
      }

      .input {
        position: absolute;
        width: 100%;
        left: 10px;
        bottom: 0;
        padding-bottom: 7px;
        color: #32325d;
        background-color: transparent;
      }

      .input::-webkit-input-placeholder {
        color: transparent;
        transition: color 0.3s cubic-bezier(0.165, 0.84, 0.44, 1);
      }

      .input::-moz-placeholder {
        color: transparent;
        transition: color 0.3s cubic-bezier(0.165, 0.84, 0.44, 1);
      }

      .input:-ms-input-placeholder {
        color: transparent;
        transition: color 0.3s cubic-bezier(0.165, 0.84, 0.44, 1);
      }

      .input.StripeElement {
        opacity: 0;
        transition: opacity 0.3s cubic-bezier(0.165, 0.84, 0.44, 1);
        will-change: opacity;
      }

      .input.focused,
      .input:not(.empty) {
        opacity: 1;
      }

      .input.focused::-webkit-input-placeholder,
      .input:not(.empty)::-webkit-input-placeholder {
        color: #cfd7df;
      }

      .input.focused::-moz-placeholder,
      .input:not(.empty)::-moz-placeholder {
        color: #cfd7df;
      }

      .input.focused:-ms-input-placeholder,
      .input:not(.empty):-ms-input-placeholder {
        color: #cfd7df;
      }

      .input.focused + label,
      .input:not(.empty) + label {
        color: #aab7c4;
        transform: scale(0.70) translateY(-25px);
        cursor: default;
        font-weight: 900;
      }

      .input.focused + label {
        color: #555;
        font-weight: 900;
      }

      .input.focused + label > i{
        display: none;
      }
      #cvc-icon {
        cursor: pointer;
        margin-left: 5px;
      }
      .input.invalid + label {
        color: #ffa27b;
      }

      .input.focused + label + .baseline {
        background-color: #555;
      }

      .input.focused.invalid + label + .baseline {
        background-color: #e25950;
      }

      input, button {
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        outline: none;
        border-style: none;
      }

      input:-webkit-autofill {
        -webkit-text-fill-color: #e39f48;
        transition: background-color 100000000s;
        -webkit-animation: 1ms void-animation-out;
      }

      .StripeElement--webkit-autofill {
        background: transparent !important;
      }

      input:active {
        background-color: #159570;
      }
      
      #card-errors {
        font-size: 12px;
        margin-top: 10px;
        /* margin-bottom: 5em; */
        margin-left: 1.5em;
        color: #E25950 !important;
      }

      .popover {
        position: absolute;
        z-index: 10;
        margin-left: 20px;
        margin-top: 90px;
        max-width: 200px;
      }
    </style>
  </head>
  <body>
    <div class="payment-form" id="payment">
      <form>
        <div class="row">
          <div class="field">
            <div id="card-number" class="input empty"></div>
            <label for="card-number">Card number</label>
          </div>
        </div>
        <div class="row">
          <div class="field half-width">
            <div id="card-expiry" class="input empty"></div>
            <label for="card-expiry">Expiry date</label>
          </div>
          <div class="field half-width">
            <div id="card-cvc" class="input empty"></div>
            <label for="card-cvc">
              Security code<i data-toggle="popover" class="far fa-question-circle" id="cvc-icon"></i>
            </label>
          </div>
        </div>
        <div id="card-errors" role="alert"></div>
      </form>

      </div>



    <script>
      function saveTokenAndChargeCard(token, donationAmount, metadata, source, key, recurring, date) {
        var url = '<%= "#{pay_url(@processor)}?key=#{@api_user.key}" %>';
        var data = JSON.stringify({
          token: token.id,
          metadata: metadata,
          source: source,
          idempotency_key: key,
          amount: donationAmount,
          recurring: recurring,
          date: date
        });

        var request = new XMLHttpRequest();
        request.open('POST', url, true);
        request.setRequestHeader('Content-Type', 'application/json');

        request.onload = function() {
          var response = JSON.parse(request.responseText);
          if (response.status) {
            data = {
              action: "donationProcessed",
              response: response
            };
            parent.postMessage(data, "*");
          } else {
            console.log("error")
          }
        };

        request.onerror = function() {
          console.log('error 2');
        }

        request.send(data);
      }

      var stripe = Stripe('<%= @stripe_publishable_key %>');
      var elements = stripe.elements();
      var elementStyles = {
        base: {
          color: '#32325D',
          fontWeight: 500,
          fontFamily: 'Source Code Pro, Consolas, Menlo, monospace',
          fontSize: '16px',
          fontSmoothing: 'antialiased',

          '::placeholder': {
            color: '#CFD7DF',
          },
          ':-webkit-autofill': {
            color: '#e39f48',
          },
        },
        invalid: {
          color: '#E25950',

          '::placeholder': {
            color: '#FFCCA5',
          },
        },
      };
      
      var inputs = document.querySelectorAll('.payment-form .input');
      Array.prototype.forEach.call(inputs, function(input) {
        input.addEventListener('focus', function() {
          input.classList.add('focused');
        });
        input.addEventListener('blur', function() {
          input.classList.remove('focused');
        });
        input.addEventListener('keyup', function() {
          if (input.value.length === 0) {
            input.classList.add('empty');
          } else {
            input.classList.remove('empty');
          }
        });
      });

      var elementClasses = {
        focus: 'focused',
        empty: 'empty',
        invalid: 'invalid',
      };
      
      var cardNumber = elements.create('cardNumber', {
        style: elementStyles,
        classes: elementClasses,
      });
      cardNumber.mount('#card-number');
      
      var cardExpiry = elements.create('cardExpiry', {
        style: elementStyles,
        classes: elementClasses,
      });
      cardExpiry.mount('#card-expiry');
      
      var cardCvc = elements.create('cardCvc', {
        style: elementStyles,
        classes: elementClasses,
      });
      cardCvc.mount('#card-cvc');

      cardNumber.addEventListener('change', function(event) {
        var displayError = document.getElementById('card-errors');
        if (event.error) {
          parent.postMessage("card number error","*");
          displayError.textContent = event.error.message;
        } else {
          parent.postMessage("card number valid","*");
          displayError.textContent = '';
        }
      });
      
      cardExpiry.addEventListener('change', function(event) {
        var displayError = document.getElementById('card-errors');
        if (event.error) {
          parent.postMessage("card exp error","*");
          displayError.textContent = event.error.message;
        } else {
          parent.postMessage("card exp valid","*");
          displayError.textContent = '';
        }
      });
      
      cardCvc.addEventListener('change', function(event) {
        var displayError = document.getElementById('card-errors');
        if (event.error) {
          parent.postMessage("card cvc error","*");
          displayError.textContent = event.error.message;
        } else {
          parent.postMessage("card cvc valid","*");
          displayError.textContent = '';
        }
      });
      
      $('#cvc-icon').popover({
        trigger: 'hover',
        container: 'body',
        html: true,
        content: '<img src="https://s3.amazonaws.com/leadnow-identity/uploads/cvv.png" style="width:100%"/>'
      });

      function registerElements(elements, donationAmount, metadata, source, key, recurring, date) {
        var form = document.getElementById('payment');
        var error = document.getElementById('card-errors');

        stripe.createToken(elements[0], metadata).then(function(result) {
          if (result.error) {
            var errorElement = document.getElementById('card-errors');
            errorElement.textContent = result.error.message;
            parent.postMessage("card details error", "*");
          } else {
            saveTokenAndChargeCard(result.token, donationAmount, metadata, source, key, recurring, date);
          }
        });
      }

      window.addEventListener("message", function(event) {
        var data = event.data;
        if (data.action === "submit") {
          registerElements([cardNumber, cardExpiry, cardCvc], data.donationAmount, data.metadata, data.source, data.idempotency_key, data.recurring, data.date);
        }
        else if (data.action === "focus") {
          cardNumber.focus();
        }
      }, false);
    </script>
  </body>
</html>